# Generated by Django 5.1
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True
    dependencies = [migrations.swappable_dependency(settings.AUTH_USER_MODEL)]
    operations = [migrations.CreateModel(name="Patient", fields=[
        ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
        ("first_name", models.CharField(max_length=100)), ("last_name", models.CharField(max_length=100)),
        ("birth_date", models.DateField(blank=True, null=True)), ("email", models.EmailField(blank=True, max_length=254)),
        ("phone", models.CharField(blank=True, max_length=30)), ("notes", models.TextField(blank=True)),
        ("created_at", models.DateTimeField(auto_now_add=True)), ("updated_at", models.DateTimeField(auto_now=True)),
        ("nutritionist", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="patients", to=settings.AUTH_USER_MODEL)),
    ], options={"ordering": ["last_name", "first_name"]})]
