# Generated by Django 5.1
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True
    dependencies = [migrations.swappable_dependency(settings.AUTH_USER_MODEL), ("patients", "0001_initial")]
    operations = [migrations.CreateModel(name="Consultation", fields=[
        ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
        ("scheduled_at", models.DateTimeField()), ("notes", models.TextField(blank=True)),
        ("created_at", models.DateTimeField(auto_now_add=True)),
        ("patient", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="consultations", to="patients.patient")),
        ("professional", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="consultations", to=settings.AUTH_USER_MODEL)),
    ], options={"ordering": ["-scheduled_at"]})]
