import { ArrowRight, ClipboardList, LineChart, MessageCircle, UsersRound } from 'lucide-react'
import { Link } from 'react-router-dom'
import heroImage from '../../../assets/images/nutrition-consultation.png'
import PublicLayout from '../../publicSite/components/PublicLayout'

const features = [
  [UsersRound, 'Expedientes organizados', 'La información de cada paciente permanece vinculada a su propio historial.'],
  [ClipboardList, 'Consultas y mediciones', 'Registra el seguimiento nutricional y consulta antecedentes sin mezclar registros.'],
  [LineChart, 'Evolución verificable', 'Compara mediciones compatibles con fechas, valores y unidades visibles.'],
]

export default function HomePage(){return <PublicLayout><section className="mx-auto grid max-w-6xl items-center gap-12 px-5 py-16 lg:grid-cols-[1fr_.9fr] lg:px-8 lg:py-24"><div><p className="inline-flex rounded-full bg-[var(--color-primary-soft)] px-4 py-2 text-xs font-bold uppercase tracking-[.14em] text-[var(--color-primary)]">Gestión nutricional clara</p><h1 className="mt-6 text-4xl font-extrabold leading-[1.08] tracking-tight text-[var(--color-heading)] sm:text-5xl lg:text-6xl">Información ordenada para acompañar cada proceso.</h1><p className="mt-6 max-w-xl text-lg leading-8 text-[var(--color-muted)]">NutriGest apoya el registro de pacientes, consultas, mediciones y seguimiento de un consultorio de nutrición.</p><div className="mt-8 flex flex-wrap gap-3"><Link to="/login" className="inline-flex min-h-12 items-center gap-2 rounded-full bg-[var(--color-primary)] px-6 font-bold text-white no-underline">Acceder al sistema <ArrowRight size={18}/></Link><Link to="/contacto" className="inline-flex min-h-12 items-center gap-2 rounded-full border border-[var(--color-border)] px-6 font-bold text-[var(--color-primary)] no-underline">Contáctanos <MessageCircle size={18}/></Link></div></div><div className="relative"><div className="absolute -inset-4 rounded-[2rem] bg-[var(--color-primary-soft)]"/><img src={heroImage} alt="Consulta de nutrición con alimentos frescos" className="relative h-[360px] w-full rounded-[2rem] object-cover shadow-sm sm:h-[440px]"/></div></section><section className="bg-[var(--color-primary-soft)] px-5 py-16 lg:px-8"><div className="mx-auto max-w-6xl"><p className="text-xs font-bold uppercase tracking-[.14em] text-[var(--color-accent)]">El sistema</p><h2 className="mt-3 max-w-2xl text-3xl font-extrabold tracking-tight text-[var(--color-heading)] sm:text-4xl">Un flujo centrado en el seguimiento nutricional.</h2><div className="mt-9 grid gap-5 md:grid-cols-3">{features.map(([Icon,title,text])=><article key={title} className="rounded-3xl border border-white/70 bg-white p-7 shadow-sm"><span className="grid h-12 w-12 place-items-center rounded-2xl bg-[var(--color-primary-soft)] text-[var(--color-primary)]"><Icon/></span><h3 className="mt-6 text-xl font-extrabold text-[var(--color-heading)]">{title}</h3><p className="mt-3 leading-7 text-[var(--color-muted)]">{text}</p></article>)}</div></div></section><section className="mx-auto grid max-w-6xl gap-8 px-5 py-16 lg:grid-cols-[1fr_auto] lg:items-center lg:px-8"><div><h2 className="text-3xl font-extrabold text-[var(--color-heading)]">¿Deseas comunicarte con el consultorio?</h2><p className="mt-3 max-w-2xl leading-7 text-[var(--color-muted)]">Envía una solicitud de contacto. No es una reserva de cita ni solicita información clínica.</p></div><Link to="/contacto" className="inline-flex min-h-12 items-center justify-center rounded-full bg-[var(--color-primary)] px-6 font-bold text-white no-underline">Enviar solicitud</Link></section></PublicLayout>}
